//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeSearch.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CodeSearchModelContainer : DbContext
    {
        public CodeSearchModelContainer()
            : base("name=CodeSearchModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Snippet> Snippets { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Note> Notes { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<CategorySnippetAssociations> CategorySnippetAssociations { get; set; }
        public virtual DbSet<ProjectNote> ProjectNotes { get; set; }
        public virtual DbSet<ProjectCategories> ProjectCategories { get; set; }
        public virtual DbSet<ProjectSnippets> ProjectSnippets { get; set; }
        public virtual DbSet<Social> Socials { get; set; }
    }
}
