//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeSearch.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectNote
    {
        public int ProjectNoteId { get; set; }
        public string ProjectNoteTitle { get; set; }
        public string ProjectNoteContent { get; set; }
        public string Created { get; set; }
        public string Modified { get; set; }
        public int ProjectProjectId { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
