//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeSearch.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategorySnippetAssociations
    {
        public int Id { get; set; }
        public int CategoryAssociationId { get; set; }
        public int SnippetAssociationId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Snippet Snippet { get; set; }
    }
}
